// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID               pgtype.UUID
	ConversationName string
	FileUrl          pgtype.Text
	Status           pgtype.Int4
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Conversationsparticipant struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Speaker        pgtype.Int4
	ConversationID pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Convert struct {
	ID              pgtype.UUID
	ConversationsID pgtype.UUID
	FileUrl         pgtype.Text
	TaskID          pgtype.UUID
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type Diarize struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	StartTime      float64
	EndTime        float64
	Speaker        int32
	TaskID         pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Participant struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Promt struct {
	ID        pgtype.UUID
	Promt     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Report struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Report         string
	PromtID        pgtype.UUID
	TaskID         pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Transcribe struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	SegmentID      pgtype.UUID
	Transcription  string
	TaskID         pgtype.UUID
	Complete       pgtype.Bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
