// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===== TRANSCRIPTION TASK =====
type MessageTranscriptionTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	StartTime     float64                `protobuf:"fixed64,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       float64                `protobuf:"fixed64,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageTranscriptionTask) Reset() {
	*x = MessageTranscriptionTask{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTranscriptionTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTranscriptionTask) ProtoMessage() {}

func (x *MessageTranscriptionTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTranscriptionTask.ProtoReflect.Descriptor instead.
func (*MessageTranscriptionTask) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MessageTranscriptionTask) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *MessageTranscriptionTask) GetStartTime() float64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MessageTranscriptionTask) GetEndTime() float64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// ===== CONVERT TASK =====
type MessageConvertTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageConvertTask) Reset() {
	*x = MessageConvertTask{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageConvertTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageConvertTask) ProtoMessage() {}

func (x *MessageConvertTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageConvertTask.ProtoReflect.Descriptor instead.
func (*MessageConvertTask) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MessageConvertTask) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

// ===== DIARIZE TASK =====
type MessageDiarizeTask struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConvertedFileUrl string                 `protobuf:"bytes,1,opt,name=converted_file_url,json=convertedFileUrl,proto3" json:"converted_file_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageDiarizeTask) Reset() {
	*x = MessageDiarizeTask{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDiarizeTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDiarizeTask) ProtoMessage() {}

func (x *MessageDiarizeTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDiarizeTask.ProtoReflect.Descriptor instead.
func (*MessageDiarizeTask) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MessageDiarizeTask) GetConvertedFileUrl() string {
	if x != nil {
		return x.ConvertedFileUrl
	}
	return ""
}

// ===== REPORT TASK =====
type MessageReportTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReportTask) Reset() {
	*x = MessageReportTask{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReportTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReportTask) ProtoMessage() {}

func (x *MessageReportTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReportTask.ProtoReflect.Descriptor instead.
func (*MessageReportTask) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MessageReportTask) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageReportTask) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// ===== SEGMENT STRUCTURE =====
type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speaker       int32                  `protobuf:"varint,1,opt,name=speaker,proto3" json:"speaker,omitempty"`
	StartTime     float64                `protobuf:"fixed64,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       float64                `protobuf:"fixed64,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Segment) GetSpeaker() int32 {
	if x != nil {
		return x.Speaker
	}
	return 0
}

func (x *Segment) GetStartTime() float64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Segment) GetEndTime() float64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ConvertTaskResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConvertedFileUrl string                 `protobuf:"bytes,1,opt,name=converted_file_url,json=convertedFileUrl,proto3" json:"converted_file_url,omitempty"`
	AudioLen         float64                `protobuf:"fixed64,2,opt,name=audio_len,json=audioLen,proto3" json:"audio_len,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConvertTaskResponse) Reset() {
	*x = ConvertTaskResponse{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertTaskResponse) ProtoMessage() {}

func (x *ConvertTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertTaskResponse.ProtoReflect.Descriptor instead.
func (*ConvertTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ConvertTaskResponse) GetConvertedFileUrl() string {
	if x != nil {
		return x.ConvertedFileUrl
	}
	return ""
}

func (x *ConvertTaskResponse) GetAudioLen() float64 {
	if x != nil {
		return x.AudioLen
	}
	return 0
}

type DiarizeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumOfSpeakers int32                  `protobuf:"varint,1,opt,name=num_of_speakers,json=numOfSpeakers,proto3" json:"num_of_speakers,omitempty"`
	Segments      []*Segment             `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiarizeTaskResponse) Reset() {
	*x = DiarizeTaskResponse{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiarizeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiarizeTaskResponse) ProtoMessage() {}

func (x *DiarizeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiarizeTaskResponse.ProtoReflect.Descriptor instead.
func (*DiarizeTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DiarizeTaskResponse) GetNumOfSpeakers() int32 {
	if x != nil {
		return x.NumOfSpeakers
	}
	return 0
}

func (x *DiarizeTaskResponse) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type TranscriptionTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcription string                 `protobuf:"bytes,1,opt,name=transcription,proto3" json:"transcription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptionTaskResponse) Reset() {
	*x = TranscriptionTaskResponse{}
	mi := &file_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionTaskResponse) ProtoMessage() {}

func (x *TranscriptionTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionTaskResponse.ProtoReflect.Descriptor instead.
func (*TranscriptionTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *TranscriptionTaskResponse) GetTranscription() string {
	if x != nil {
		return x.Transcription
	}
	return ""
}

type ReportTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResponse) Reset() {
	*x = ReportTaskResponse{}
	mi := &file_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResponse) ProtoMessage() {}

func (x *ReportTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ReportTaskResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ErrorTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorTaskResponse) Reset() {
	*x = ErrorTaskResponse{}
	mi := &file_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorTaskResponse) ProtoMessage() {}

func (x *ErrorTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorTaskResponse.ProtoReflect.Descriptor instead.
func (*ErrorTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WrapperTask struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to Task:
	//
	//	*WrapperTask_Convert
	//	*WrapperTask_Diarize
	//	*WrapperTask_Transcription
	//	*WrapperTask_SemiReport
	//	*WrapperTask_Report
	Task          isWrapperTask_Task `protobuf_oneof:"task"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperTask) Reset() {
	*x = WrapperTask{}
	mi := &file_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperTask) ProtoMessage() {}

func (x *WrapperTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperTask.ProtoReflect.Descriptor instead.
func (*WrapperTask) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{10}
}

func (x *WrapperTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WrapperTask) GetTask() isWrapperTask_Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *WrapperTask) GetConvert() *MessageConvertTask {
	if x != nil {
		if x, ok := x.Task.(*WrapperTask_Convert); ok {
			return x.Convert
		}
	}
	return nil
}

func (x *WrapperTask) GetDiarize() *MessageDiarizeTask {
	if x != nil {
		if x, ok := x.Task.(*WrapperTask_Diarize); ok {
			return x.Diarize
		}
	}
	return nil
}

func (x *WrapperTask) GetTranscription() *MessageTranscriptionTask {
	if x != nil {
		if x, ok := x.Task.(*WrapperTask_Transcription); ok {
			return x.Transcription
		}
	}
	return nil
}

func (x *WrapperTask) GetSemiReport() *MessageReportTask {
	if x != nil {
		if x, ok := x.Task.(*WrapperTask_SemiReport); ok {
			return x.SemiReport
		}
	}
	return nil
}

func (x *WrapperTask) GetReport() *MessageReportTask {
	if x != nil {
		if x, ok := x.Task.(*WrapperTask_Report); ok {
			return x.Report
		}
	}
	return nil
}

type isWrapperTask_Task interface {
	isWrapperTask_Task()
}

type WrapperTask_Convert struct {
	Convert *MessageConvertTask `protobuf:"bytes,2,opt,name=convert,proto3,oneof"`
}

type WrapperTask_Diarize struct {
	Diarize *MessageDiarizeTask `protobuf:"bytes,3,opt,name=diarize,proto3,oneof"`
}

type WrapperTask_Transcription struct {
	Transcription *MessageTranscriptionTask `protobuf:"bytes,4,opt,name=transcription,proto3,oneof"`
}

type WrapperTask_SemiReport struct {
	SemiReport *MessageReportTask `protobuf:"bytes,5,opt,name=semi_report,json=semiReport,proto3,oneof"`
}

type WrapperTask_Report struct {
	Report *MessageReportTask `protobuf:"bytes,6,opt,name=report,proto3,oneof"`
}

func (*WrapperTask_Convert) isWrapperTask_Task() {}

func (*WrapperTask_Diarize) isWrapperTask_Task() {}

func (*WrapperTask_Transcription) isWrapperTask_Task() {}

func (*WrapperTask_SemiReport) isWrapperTask_Task() {}

func (*WrapperTask_Report) isWrapperTask_Task() {}

type WrapperResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WrapperResponse_Convert
	//	*WrapperResponse_Diarize
	//	*WrapperResponse_Transcription
	//	*WrapperResponse_SemiReport
	//	*WrapperResponse_Report
	//	*WrapperResponse_Error
	Payload       isWrapperResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperResponse) Reset() {
	*x = WrapperResponse{}
	mi := &file_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperResponse) ProtoMessage() {}

func (x *WrapperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperResponse.ProtoReflect.Descriptor instead.
func (*WrapperResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{11}
}

func (x *WrapperResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WrapperResponse) GetPayload() isWrapperResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WrapperResponse) GetConvert() *ConvertTaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*WrapperResponse_Convert); ok {
			return x.Convert
		}
	}
	return nil
}

func (x *WrapperResponse) GetDiarize() *DiarizeTaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*WrapperResponse_Diarize); ok {
			return x.Diarize
		}
	}
	return nil
}

func (x *WrapperResponse) GetTranscription() *TranscriptionTaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*WrapperResponse_Transcription); ok {
			return x.Transcription
		}
	}
	return nil
}

func (x *WrapperResponse) GetSemiReport() *ReportTaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*WrapperResponse_SemiReport); ok {
			return x.SemiReport
		}
	}
	return nil
}

func (x *WrapperResponse) GetReport() *ReportTaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*WrapperResponse_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *WrapperResponse) GetError() *ErrorTaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*WrapperResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isWrapperResponse_Payload interface {
	isWrapperResponse_Payload()
}

type WrapperResponse_Convert struct {
	Convert *ConvertTaskResponse `protobuf:"bytes,2,opt,name=convert,proto3,oneof"`
}

type WrapperResponse_Diarize struct {
	Diarize *DiarizeTaskResponse `protobuf:"bytes,3,opt,name=diarize,proto3,oneof"`
}

type WrapperResponse_Transcription struct {
	Transcription *TranscriptionTaskResponse `protobuf:"bytes,4,opt,name=transcription,proto3,oneof"`
}

type WrapperResponse_SemiReport struct {
	SemiReport *ReportTaskResponse `protobuf:"bytes,5,opt,name=semi_report,json=semiReport,proto3,oneof"`
}

type WrapperResponse_Report struct {
	Report *ReportTaskResponse `protobuf:"bytes,6,opt,name=report,proto3,oneof"`
}

type WrapperResponse_Error struct {
	Error *ErrorTaskResponse `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*WrapperResponse_Convert) isWrapperResponse_Payload() {}

func (*WrapperResponse_Diarize) isWrapperResponse_Payload() {}

func (*WrapperResponse_Transcription) isWrapperResponse_Payload() {}

func (*WrapperResponse_SemiReport) isWrapperResponse_Payload() {}

func (*WrapperResponse_Report) isWrapperResponse_Payload() {}

func (*WrapperResponse_Error) isWrapperResponse_Payload() {}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\bmessages\"o\n" +
	"\x18MessageTranscriptionTask\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x01R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x01R\aendTime\"/\n" +
	"\x12MessageConvertTask\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\"B\n" +
	"\x12MessageDiarizeTask\x12,\n" +
	"\x12converted_file_url\x18\x01 \x01(\tR\x10convertedFileUrl\"E\n" +
	"\x11MessageReportTask\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"]\n" +
	"\aSegment\x12\x18\n" +
	"\aspeaker\x18\x01 \x01(\x05R\aspeaker\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x01R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x01R\aendTime\"`\n" +
	"\x13ConvertTaskResponse\x12,\n" +
	"\x12converted_file_url\x18\x01 \x01(\tR\x10convertedFileUrl\x12\x1b\n" +
	"\taudio_len\x18\x02 \x01(\x01R\baudioLen\"l\n" +
	"\x13DiarizeTaskResponse\x12&\n" +
	"\x0fnum_of_speakers\x18\x01 \x01(\x05R\rnumOfSpeakers\x12-\n" +
	"\bsegments\x18\x02 \x03(\v2\x11.messages.SegmentR\bsegments\"A\n" +
	"\x19TranscriptionTaskResponse\x12$\n" +
	"\rtranscription\x18\x01 \x01(\tR\rtranscription\"(\n" +
	"\x12ReportTaskResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\")\n" +
	"\x11ErrorTaskResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xe5\x02\n" +
	"\vWrapperTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x128\n" +
	"\aconvert\x18\x02 \x01(\v2\x1c.messages.MessageConvertTaskH\x00R\aconvert\x128\n" +
	"\adiarize\x18\x03 \x01(\v2\x1c.messages.MessageDiarizeTaskH\x00R\adiarize\x12J\n" +
	"\rtranscription\x18\x04 \x01(\v2\".messages.MessageTranscriptionTaskH\x00R\rtranscription\x12>\n" +
	"\vsemi_report\x18\x05 \x01(\v2\x1b.messages.MessageReportTaskH\x00R\n" +
	"semiReport\x125\n" +
	"\x06report\x18\x06 \x01(\v2\x1b.messages.MessageReportTaskH\x00R\x06reportB\x06\n" +
	"\x04task\"\xa6\x03\n" +
	"\x0fWrapperResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x129\n" +
	"\aconvert\x18\x02 \x01(\v2\x1d.messages.ConvertTaskResponseH\x00R\aconvert\x129\n" +
	"\adiarize\x18\x03 \x01(\v2\x1d.messages.DiarizeTaskResponseH\x00R\adiarize\x12K\n" +
	"\rtranscription\x18\x04 \x01(\v2#.messages.TranscriptionTaskResponseH\x00R\rtranscription\x12?\n" +
	"\vsemi_report\x18\x05 \x01(\v2\x1c.messages.ReportTaskResponseH\x00R\n" +
	"semiReport\x126\n" +
	"\x06report\x18\x06 \x01(\v2\x1c.messages.ReportTaskResponseH\x00R\x06report\x123\n" +
	"\x05error\x18\a \x01(\v2\x1b.messages.ErrorTaskResponseH\x00R\x05errorB\t\n" +
	"\apayloadB\x13Z\x11main/pkg/messagesb\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_messages_proto_goTypes = []any{
	(*MessageTranscriptionTask)(nil),  // 0: messages.MessageTranscriptionTask
	(*MessageConvertTask)(nil),        // 1: messages.MessageConvertTask
	(*MessageDiarizeTask)(nil),        // 2: messages.MessageDiarizeTask
	(*MessageReportTask)(nil),         // 3: messages.MessageReportTask
	(*Segment)(nil),                   // 4: messages.Segment
	(*ConvertTaskResponse)(nil),       // 5: messages.ConvertTaskResponse
	(*DiarizeTaskResponse)(nil),       // 6: messages.DiarizeTaskResponse
	(*TranscriptionTaskResponse)(nil), // 7: messages.TranscriptionTaskResponse
	(*ReportTaskResponse)(nil),        // 8: messages.ReportTaskResponse
	(*ErrorTaskResponse)(nil),         // 9: messages.ErrorTaskResponse
	(*WrapperTask)(nil),               // 10: messages.WrapperTask
	(*WrapperResponse)(nil),           // 11: messages.WrapperResponse
}
var file_proto_messages_proto_depIdxs = []int32{
	4,  // 0: messages.DiarizeTaskResponse.segments:type_name -> messages.Segment
	1,  // 1: messages.WrapperTask.convert:type_name -> messages.MessageConvertTask
	2,  // 2: messages.WrapperTask.diarize:type_name -> messages.MessageDiarizeTask
	0,  // 3: messages.WrapperTask.transcription:type_name -> messages.MessageTranscriptionTask
	3,  // 4: messages.WrapperTask.semi_report:type_name -> messages.MessageReportTask
	3,  // 5: messages.WrapperTask.report:type_name -> messages.MessageReportTask
	5,  // 6: messages.WrapperResponse.convert:type_name -> messages.ConvertTaskResponse
	6,  // 7: messages.WrapperResponse.diarize:type_name -> messages.DiarizeTaskResponse
	7,  // 8: messages.WrapperResponse.transcription:type_name -> messages.TranscriptionTaskResponse
	8,  // 9: messages.WrapperResponse.semi_report:type_name -> messages.ReportTaskResponse
	8,  // 10: messages.WrapperResponse.report:type_name -> messages.ReportTaskResponse
	9,  // 11: messages.WrapperResponse.error:type_name -> messages.ErrorTaskResponse
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	file_proto_messages_proto_msgTypes[10].OneofWrappers = []any{
		(*WrapperTask_Convert)(nil),
		(*WrapperTask_Diarize)(nil),
		(*WrapperTask_Transcription)(nil),
		(*WrapperTask_SemiReport)(nil),
		(*WrapperTask_Report)(nil),
	}
	file_proto_messages_proto_msgTypes[11].OneofWrappers = []any{
		(*WrapperResponse_Convert)(nil),
		(*WrapperResponse_Diarize)(nil),
		(*WrapperResponse_Transcription)(nil),
		(*WrapperResponse_SemiReport)(nil),
		(*WrapperResponse_Report)(nil),
		(*WrapperResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
