pg:
  host: 127.0.0.1
  port: 5432
  user: virus
  password: postgres
  database: db

server:
  host: localhost
  port: 8080

s3:
  endpoint: http://localhost:9000
  access_key: virus
  secret_key: password
  bucket: bucker
  region: ru-central1
  minio: true

api:
  baseurl: "http://localhost:8000"
  timeout: 10