pg:
  host: {{ .PG_HOST}}
  port: {{ .PG_PORT}}
  user: {{ .PG_USER}}
  password: {{ .PG_PASSWORD}}
  database: {{ .PG_DATABASE}}

server:
  host: {{ .SERVER_HOST}}
  port: {{ .SERVER_PORT}}

logger:
  log_level: {{ .LOG_LEVEL}}
  encoding: {{ .LOG_ENCODING}}

s3:
  endpoint: {{ .S3_ENDPOINT}}
  access_key: {{ .S3_ACCESS_KEY}}
  secret_key: {{ .S3_SECRET_KEY}}
  bucket: {{ .S3_BUCKET}}
  region: {{ .S3_REGION}}
  minio: {{ .S3_MINIO}}

producer:
  brokers:
    - {{ .PRODUCER_BROKER}}
  topic: {{ .PRODUCER_TOPIC}}

consumer:
  brokers:
    - {{ .CONSUMER_BROKER}}
  topic: {{ .CONSUMER_TOPIC}}
  group_id: {{ .CONSUMER_GROUP_ID}}