pg:
  host: 127.0.0.1
  port: 5432
  user: virus
  password: postgres
  database: db

server:
  host: 0.0.0.0
  port: 8080
  log_level: "debug"

s3:
  endpoint: http://localhost:9000
  access_key: virus
  secret_key: password
  bucket: bucket
  region: ru-central1
  minio: true

producer:
  brokers:
    - "localhost:9092"
  topic: "task"

consumer:
  brokers:
    - "localhost:9092"
  topic: "callback"
  group_id: "go_consumer"
